swagger:
  paths: /api.*
  api.info:
    title: @app.id@
    description: @pom.description@ Documentation
    contact: @swagger.project.contact@
    version: @pom.version@
    license: license
    licenseUrl: http://easyms.fr/LICENSE-0.0.1.html
